config/routes.rb
Rails.application.routes.draw do
  # Devise routes for user authentication
  devise_for :users

  # Root path for the application (homepage)
  root to: "properties#index"

  # Nested routes for properties and bookings
  resources :properties do
    resources :bookings, only: [:new, :create]  # Bookings can be created under properties
    collection do
      get :search  # Adding search route for properties
      get :suggestions  # Route for AJAX suggestions
    end
  end

  # nnested routes for bookings and reviews
  resources :bookings do
    resources :reviews, only: [:create, :destroy]  # Reviews can be created or deleted under bookings
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">

  <div class="d-flex justify-content-between align-items-center mx-4">

    <div>
      <ul class="list-group list-group-horizontal fs-5">
        <li class="list-group p-3"><span>2024 Le Wagon Project <span></li>
        <li class="list-group p-3"><span>About the authors<span></li>
      </ul>
    </div>

    <div>
      <ul class="list-group list-group-horizontal">
        <li class="footer_item list-group"><i class="fa-brands fa-github"></i></li>
        <li class="footer_item list-group"><i class="fa-brands fa-facebook"></i></li>
        <li class="footer_item list-group"><i class="fa-brands fa-x-twitter"></i></li>
        <li class="footer_item list-group"><i class="fa-brands fa-instagram"></i></li>
      </ul>
    </div>

  </div>

</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color: white;">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to new_property_path, class: 'btn btn-light rounded-pill d-flex align-items-center p-3 border border-info me-4' do %>
              <i class="fas fa-plus me-2"></i> <!-- ffont Awesome Icon für "Add" -->
              Add a new property
            <% end %>
          </li>
        <% end %>
      </ul>

      <div class="d-flex align-items-center">
        <!-- menu and profil button -->
        <div class="btn-group">
          <button type="button" class="btn btn-light rounded-pill d-flex align-items-center p-3 border border-info" style="height: 60px;" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-bars me-4"></i>
            <i class="fas fa-user"></i>
          </button>
          <ul class="dropdown-menu dropdown-menu-end">
            <% if user_signed_in? %>
              <li><%= link_to "home", root_path, class: "dropdown-item" %></li>
              <li><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %></li>
              <li><%= link_to "My Bookings", bookings_path, class: "dropdown-item" %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path, class: "dropdown-item" %></li>
              <li><%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>